/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as ApiVideoIdRouteImport } from './routes/api/video.$id'
import { Route as ApiExportIdRouteImport } from './routes/api/export.$id'
import { Route as AuthenticatedSettingsApiRouteImport } from './routes/_authenticated/settings.api'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiVideoIdRoute = ApiVideoIdRouteImport.update({
  id: '/api/video/$id',
  path: '/api/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportIdRoute = ApiExportIdRouteImport.update({
  id: '/api/export/$id',
  path: '/api/export/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsApiRoute =
  AuthenticatedSettingsApiRouteImport.update({
    id: '/settings/api',
    path: '/settings/api',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/api/export/$id': typeof ApiExportIdRoute
  '/api/video/$id': typeof ApiVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/api/export/$id': typeof ApiExportIdRoute
  '/api/video/$id': typeof ApiVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/settings/api': typeof AuthenticatedSettingsApiRoute
  '/api/export/$id': typeof ApiExportIdRoute
  '/api/video/$id': typeof ApiVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/studio'
    | '/settings/api'
    | '/api/export/$id'
    | '/api/video/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/studio'
    | '/settings/api'
    | '/api/export/$id'
    | '/api/video/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/studio'
    | '/_authenticated/settings/api'
    | '/api/export/$id'
    | '/api/video/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiExportIdRoute: typeof ApiExportIdRoute
  ApiVideoIdRoute: typeof ApiVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/video/$id': {
      id: '/api/video/$id'
      path: '/api/video/$id'
      fullPath: '/api/video/$id'
      preLoaderRoute: typeof ApiVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/$id': {
      id: '/api/export/$id'
      path: '/api/export/$id'
      fullPath: '/api/export/$id'
      preLoaderRoute: typeof ApiExportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/api': {
      id: '/_authenticated/settings/api'
      path: '/settings/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof AuthenticatedSettingsApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedSettingsApiRoute: typeof AuthenticatedSettingsApiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedSettingsApiRoute: AuthenticatedSettingsApiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiExportIdRoute: ApiExportIdRoute,
  ApiVideoIdRoute: ApiVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
